trigger:
 branches:
   include:
     - main

pool: my_pool 

stages:
  - stage:
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'infra_pipline'
            backendAzureRmStorageAccountName: 'statemanage'
            backendAzureRmContainerName: 'statemanage'
            backendAzureRmKey: 'terraform.tfstate'
            